-- EXPLORATORY DATA ANALYSIS

SELECT * FROM LAYOFFS_STAGING2;

SELECT MAX(TOTAL_LAID_OFF), MAX(PERCENTAGE_LAID_OFF) FROM LAYOFFS_STAGING2;

SELECT * FROM LAYOFFS_STAGING2
WHERE PERCENTAGE_LAID_OFF =1
ORDER BY FUNDS_RAISED_MILLIONS DESC, TOTAL_LAID_OFF DESC;

SELECT COMPANY, SUM(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2
GROUP BY COMPANY
ORDER BY 2 DESC;

SELECT MIN(`date`),MAX(`date`) FROM LAYOFFS_STAGING2;

SELECT INDUSTRY, SUM(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2
GROUP BY INDUSTRY
ORDER BY 2 DESC;

SELECT COUNTRY, SUM(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2
GROUP BY COUNTRY
ORDER BY 2 DESC;

SELECT `date`, SUM(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2
GROUP BY `date`
ORDER BY 2 DESC;

SELECT year(`date`), SUM(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2
GROUP BY year(`date`)
ORDER BY 2 DESC;

SELECT STAGE, SUM(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2
GROUP BY STAGE
ORDER BY 2 DESC;

WITH ROLLING_TOTAL AS
(
	SELECT SUBSTRING(`date`,1,7) as `MONTH`, SUM(TOTAL_LAID_OFF) AS LAYOFFS
	FROM LAYOFFS_STAGING2
	WHERE SUBSTRING(`date`,1,7) IS NOT NULL
	GROUP BY `MONTH`
    ORDER BY 1
)
SELECT `MONTH`, LAYOFFS, SUM(LAYOFFS)OVER(ORDER BY `MONTH`) AS ROLLING_LAYOFFS FROM ROLLING_TOTAL;

WITH COMPANY_YEAR AS
(
	SELECT COMPANY, YEAR(`date`) AS `YEAR`, SUM(TOTAL_LAID_OFF) AS LAYOFFS FROM LAYOFFS_STAGING2
	GROUP BY COMPANY,`YEAR`
), 
COMPANY_RANK AS 
(
	SELECT *, DENSE_RANK()OVER(PARTITION BY `YEAR` ORDER BY LAYOFFS DESC) AS RNK FROM COMPANY_YEAR
	WHERE `YEAR` IS NOT NULL
)
SELECT * FROM COMPANY_RANK
WHERE RNK <=5
ORDER BY 2, 3 DESC;









