-- ============================================================
-- DATA CLEANING - LAYOFFS DATASET
-- ============================================================
-- STEPS:
--   1. REMOVE DUPLICATES IF THE DATA SHOULD NOT HAVE ANY
--   2. STANDARDIZE DATA (CONSISTENT FORMATTING AND VALUES)
--   3. HANDLE NULL, NaN, AND BLANK VALUES
--   4. REMOVE UNNECESSARY COLUMNS AND ROWS
--
-- NOTE: ALL CHANGES ARE MADE ON STAGING TABLES, NOT THE RAW DATA.
--       THIS ENSURES THE ORIGINAL LAYOFFS TABLE IS NEVER MODIFIED.
-- ============================================================

-- PREVIEW THE RAW DATA BEFORE DOING ANYTHING
SELECT * FROM LAYOFFS;

-- CREATE THE FIRST STAGING TABLE BY COPYING ALL RAW DATA INTO IT.
-- THIS IS WHERE WE WILL DO OUR INITIAL WORK BEFORE MOVING TO STAGING2.

CREATE TABLE `layoffs_staging` (
  `company` TEXT,
  `location` TEXT,
  `industry` TEXT,
  `total_laid_off` INT DEFAULT NULL,
  `percentage_laid_off` TEXT,
  `date` TEXT,
  `stage` TEXT,
  `country` TEXT,
  `funds_raised_millions` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SELECT * FROM LAYOFFS_STAGING;

INSERT LAYOFFS_STAGING
SELECT * FROM LAYOFFS;

-- ============================================================
-- STEP 1: REMOVE DUPLICATES
-- ============================================================

-- USE ROW_NUMBER() TO ASSIGN A RANK TO EACH ROW WITHIN GROUPS OF MATCHING RECORDS.
-- ANY ROW WITH ROW_NUM > 1 IS A DUPLICATE OF THE FIRST OCCURRENCE.

WITH DUPLICATE_CTE AS (
	SELECT *,
	ROW_NUMBER() OVER(PARTITION BY COMPANY, LOCATION, INDUSTRY, TOTAL_LAID_OFF, `date`, STAGE, COUNTRY, FUNDS_RAISED_MILLIONS) AS ROW_NUM 
	FROM LAYOFFS_STAGING
)
SELECT * FROM DUPLICATE_CTE WHERE ROW_NUM > 1;

-- BEFORE DELETING, MANUALLY VERIFY A SPECIFIC COMPANY TO CONFIRM THE FLAGGED ROWS ARE
-- TRUE DUPLICATES AND NOT LEGITIMATE SEPARATE ENTRIES (E.G. MULTIPLE LAYOFF ROUNDS).

SELECT * FROM LAYOFFS_STAGING WHERE COMPANY = 'casper';

-- NOTE: YOU CANNOT DELETE DIRECTLY FROM A CTE IN MySQL.
-- THE STATEMENT BELOW WILL FAIL -- IT IS LEFT HERE AS A REFERENCE FOR WHY WE NEED A SECOND STAGING TABLE.

WITH DUPLICATE_CTE AS (
	SELECT *,
	ROW_NUMBER() OVER(PARTITION BY COMPANY, LOCATION, INDUSTRY, TOTAL_LAID_OFF, `date`, STAGE, COUNTRY, FUNDS_RAISED_MILLIONS) AS ROW_NUM 
	FROM LAYOFFS_STAGING
)
DELETE FROM DUPLICATE_CTE WHERE ROW_NUM > 1;


-- CREATE A SECOND STAGING TABLE THAT INCLUDES THE ROW_NUM COLUMN.
-- THIS ALLOWS US TO IDENTIFY AND DELETE DUPLICATES DIRECTLY FROM THE TABLE.

CREATE TABLE `layoffs_staging2` (
  `company` TEXT,
  `location` TEXT,
  `industry` TEXT,
  `total_laid_off` INT DEFAULT NULL,
  `percentage_laid_off` TEXT,
  `date` TEXT,
  `stage` TEXT,
  `country` TEXT,
  `funds_raised_millions` INT DEFAULT NULL,
  `row_num` INT 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- POPULATE STAGING2 WITH ALL ROWS FROM STAGING1, INCLUDING THE ROW_NUM CALCULATION

INSERT INTO LAYOFFS_STAGING2
	SELECT *,
	ROW_NUMBER() OVER(PARTITION BY COMPANY, LOCATION, INDUSTRY, TOTAL_LAID_OFF, `date`, STAGE, COUNTRY, FUNDS_RAISED_MILLIONS) AS ROW_NUM 
	FROM LAYOFFS_STAGING;

-- DELETE ALL ROWS WHERE ROW_NUM > 1, AS THESE ARE CONFIRMED DUPLICATES

DELETE FROM LAYOFFS_STAGING2
	WHERE ROW_NUM > 1;

-- VERIFY DUPLICATES HAVE BEEN REMOVED

SELECT * FROM LAYOFFS_STAGING2;


-- ============================================================
-- STEP 2: STANDARDIZE DATA
-- ============================================================

-- CHECK FOR LEADING OR TRAILING SPACES IN COMPANY NAMES

SELECT TRIM(COMPANY) FROM LAYOFFS_STAGING2;

-- REMOVE LEADING AND TRAILING SPACES FROM ALL COMPANY NAMES

UPDATE LAYOFFS_STAGING2
SET COMPANY = TRIM(COMPANY);

-- REVIEW ALL DISTINCT INDUSTRY VALUES TO SPOT INCONSISTENCIES OR VARIATIONS

SELECT DISTINCT INDUSTRY FROM LAYOFFS_STAGING2
ORDER BY 1;

-- PREVIEW ROWS WHERE INDUSTRY CONTAINS VARIATIONS OF 'CRYPTO'

-- (E.G. 'Crypto Currency', 'CryptoCurrency', ETC.)
SELECT * FROM LAYOFFS_STAGING2
WHERE INDUSTRY LIKE 'Crypto%';

-- CONSOLIDATE ALL CRYPTO-RELATED INDUSTRY LABELS INTO A SINGLE STANDARD VALUE

UPDATE LAYOFFS_STAGING2 
SET INDUSTRY = 'Crypto'
WHERE INDUSTRY LIKE 'Crypto%';

-- CHECK FOR COUNTRY NAME INCONSISTENCIES -- 'United States' APPEARS WITH A TRAILING PERIOD IN SOME ROWS

SELECT DISTINCT COUNTRY, TRIM(TRAILING '.' FROM COUNTRY) FROM LAYOFFS_STAGING2
WHERE COUNTRY LIKE 'United States%';

-- REMOVE THE TRAILING PERIOD FROM AFFECTED COUNTRY ENTRIES

UPDATE LAYOFFS_STAGING2
SET COUNTRY = TRIM(TRAILING '.' FROM COUNTRY)
WHERE COUNTRY LIKE 'United States%';

-- VERIFY ALL COUNTRY NAMES ARE NOW CLEAN AND CONSISTENT

SELECT DISTINCT COUNTRY FROM LAYOFFS_STAGING2
ORDER BY 1;

-- PREVIEW THE CURRENT DATE FORMAT AND WHAT IT WILL LOOK LIKE AFTER CONVERSION.
-- THE DATE COLUMN IS STORED AS TEXT IN MM/DD/YYYY FORMAT AND NEEDS TO BE STANDARDIZED.

SELECT `date`,
STR_TO_DATE(`date`, '%m/%d/%Y') FROM LAYOFFS_STAGING2;

-- CONVERT THE DATE STRINGS TO PROPER YYYY-MM-DD FORMAT

UPDATE LAYOFFS_STAGING2
SET `date` = STR_TO_DATE(`date`, '%m/%d/%Y');

-- VERIFY THE DATE VALUES LOOK CORRECT AFTER CONVERSION

SELECT `date` FROM LAYOFFS_STAGING2;

-- NOW THAT THE VALUES ARE FORMATTED CORRECTLY, CHANGE THE COLUMN'S DATA TYPE FROM TEXT TO DATE.
-- THIS ENABLES PROPER DATE FILTERING, SORTING, AND FUNCTIONS LIKE DATE_FORMAT().
-- IMPORTANT: NEVER ALTER COLUMN TYPES ON THE RAW TABLE -- ONLY DO THIS ON STAGING TABLES.

ALTER TABLE LAYOFFS_STAGING2
MODIFY COLUMN `date` DATE;

-- VERIFY THE FULL TABLE LOOKS CORRECT AFTER ALL STANDARDIZATION CHANGES

SELECT * FROM LAYOFFS_STAGING2;

-- SUMMARY OF CHANGES MADE IN STEP 2:
--   - REMOVED LEADING AND TRAILING SPACES FROM COMPANY NAMES
--   - CONSOLIDATED VARIATIONS OF CRYPTO INDUSTRY LABELS INTO ONE STANDARD VALUE
--   - REMOVED TRAILING PERIODS FROM COUNTRY NAMES (E.G. 'United States.')
--   - CONVERTED DATE COLUMN FROM TEXT (MM/DD/YYYY) TO DATE TYPE (YYYY-MM-DD)


-- ============================================================
-- STEP 3: HANDLE NULLS AND BLANK VALUES
-- ============================================================

-- FIND ALL ROWS WHERE INDUSTRY IS EITHER NULL OR AN EMPTY STRING

SELECT * FROM LAYOFFS_STAGING2
WHERE INDUSTRY IS NULL OR INDUSTRY = '';

-- CHECK A SPECIFIC COMPANY (AIRBNB) TO SEE IF OTHER ROWS FOR THAT COMPANY HAVE AN INDUSTRY VALUE.
-- IF THEY DO, WE CAN USE THOSE ROWS TO FILL IN THE MISSING VALUES.

SELECT * FROM LAYOFFS_STAGING2
WHERE COMPANY = 'Airbnb';

-- USE A SELF JOIN TO FIND ROWS WITH A MISSING INDUSTRY WHERE ANOTHER ROW FOR THE SAME
-- COMPANY AND LOCATION DOES HAVE AN INDUSTRY VALUE THAT CAN BE USED TO FILL IT IN

SELECT T1.INDUSTRY, T2.INDUSTRY FROM LAYOFFS_STAGING2 T1
JOIN LAYOFFS_STAGING2 T2
	ON T1.COMPANY = T2.COMPANY
	AND T1.LOCATION = T2.LOCATION
WHERE T1.INDUSTRY IS NULL AND T2.INDUSTRY IS NOT NULL;

-- FIRST, CONVERT ALL BLANK INDUSTRY STRINGS TO NULL SO THEY CAN BE HANDLED UNIFORMLY

UPDATE LAYOFFS_STAGING2 
SET INDUSTRY = NULL
WHERE INDUSTRY = '';

-- NOW FILL IN THE NULL INDUSTRY VALUES USING THE MATCHING ROWS IDENTIFIED BY THE SELF JOIN ABOVE

UPDATE LAYOFFS_STAGING2 T1
JOIN LAYOFFS_STAGING2 T2
	ON T1.COMPANY = T2.COMPANY
SET T1.INDUSTRY = T2.INDUSTRY
WHERE T1.INDUSTRY IS NULL AND T2.INDUSTRY IS NOT NULL;

-- CHECK FOR ANY COMPANIES THAT STILL HAVE NO INDUSTRY VALUE AFTER THE UPDATE.
-- BALLY'S IS THE ONLY REMAINING CASE AND HAS NO OTHER ROWS TO PULL AN INDUSTRY FROM,
-- SO IT WILL REMAIN NULL.

SELECT COMPANY FROM LAYOFFS_STAGING2
WHERE COMPANY LIKE 'Bally%';

-- REVIEW THE FULL TABLE AFTER NULL HANDLING

SELECT * FROM LAYOFFS_STAGING2;

-- NOTE: ROWS WHERE BOTH TOTAL_LAID_OFF AND PERCENTAGE_LAID_OFF ARE NULL CANNOT BE
-- RELIABLY FILLED IN WITHOUT EXTERNAL DATA (E.G. WEB SCRAPING).
-- SINCE THESE COLUMNS ARE CRITICAL TO OUR ANALYSIS, KEEPING THESE ROWS WOULD DILUTE
-- THE RESULTS. THEY WILL BE REMOVED IN THE NEXT STEP.


-- ============================================================
-- STEP 4: REMOVE UNNECESSARY COLUMNS AND ROWS
-- ============================================================

-- IDENTIFY ROWS WHERE BOTH KEY METRICS ARE NULL -- THESE ROWS HAVE NO ANALYTICAL VALUE

SELECT * FROM LAYOFFS_STAGING2
WHERE TOTAL_LAID_OFF IS NULL
AND PERCENTAGE_LAID_OFF IS NULL;

-- DELETE ALL ROWS WHERE BOTH TOTAL_LAID_OFF AND PERCENTAGE_LAID_OFF ARE NULL

DELETE FROM LAYOFFS_STAGING2
WHERE TOTAL_LAID_OFF IS NULL AND PERCENTAGE_LAID_OFF IS NULL;

-- VERIFY THE ROWS WERE DELETED SUCCESSFULLY

SELECT * FROM LAYOFFS_STAGING2;

-- DROP THE ROW_NUM COLUMN SINCE IT WAS ONLY NEEDED TO IDENTIFY AND REMOVE DUPLICATES

ALTER TABLE LAYOFFS_STAGING2
DROP COLUMN ROW_NUM;

-- FINAL CHECK -- THE CLEANED TABLE IS NOW READY FOR ANALYSIS

SELECT * FROM LAYOFFS_STAGING2;
